### ISSUE TITLE
name and feedback are not properly stored; rspec tests fail

### ISSUE THREAD

**Issue by paul-e-allen** [aws-samples/serverless-sinatra-sample#15]
I deployed the solution using directions in README.md. The Feedback portion of the app does not save "name" or "feedback" fields in Dynamo DB properly. Maybe this is due to an AWS API change somewhere along the way?

I have also tried deploying the solution using the pipeline-cfn.yaml CloudFormation template. CodePipeline deployments of the solution fail because rspec test fail on this same issue:

````
# rspec
..F.

Failures:

  1) HelloWorld Service should POST params to API feedback endpoint with success
     Failure/Error: item.save! # raise an exception if save fails
     
       #<Aws::DynamoDB::Client> received :put_item with unexpected arguments
         expected: ({:condition_expression=>be a kind of String, :expression_attribute_names=>be a kind of Hash, :item=>{...g, "name"=>"Tomas", "ts"=>be within 3 of 1554471349}, :table_name=>"FeedbackServerlessSinatraTable"})
              got: ({:condition_expression=>"attribute_not_exists(#H)", :expression_attribute_names=>{"#H"=>"id"}, :item=...412f-5057-4b7b-bf10-ae7a143b9689", "ts"=>1554471349}, :table_name=>"FeedbackServerlessSinatraTable"})
       Diff:
       @@ -1,9 +1,5 @@
       -[{:condition_expression=>be a kind of String,
       -  :expression_attribute_names=>be a kind of Hash,
       -  :item=>
       -   {"feedback"=>"AWS Lambda + Ruby == <3",
       -    "id"=>be a kind of String,
       -    "name"=>"Tomas",
       -    "ts"=>be within 3 of 1554471349},
       +[{:condition_expression=>"attribute_not_exists(#H)",
       +  :expression_attribute_names=>{"#H"=>"id"},
       +  :item=>{"id"=>"db13412f-5057-4b7b-bf10-ae7a143b9689", "ts"=>1554471349},
          :table_name=>"FeedbackServerlessSinatraTable"}]
       
     # /usr/local/bundle/gems/aws-record-2.3.0/lib/aws-record/record/item_operations.rb:226:in `_perform_save'
     # /usr/local/bundle/gems/aws-record-2.3.0/lib/aws-record/record/item_operations.rb:80:in `save'
     # /usr/local/bundle/gems/aws-record-2.3.0/lib/aws-record/record/dirty_tracking.rb:275:in `save'
     # /usr/local/bundle/gems/aws-record-2.3.0/lib/aws-record/record/item_operations.rb:48:in `save!'
     # ./app/server.rb:64:in `block in <top (required)>'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
     # /usr/local/bundle/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
     # /usr/local/bundle/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
     # /usr/local/bundle/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
     # /usr/local/bundle/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
     # /usr/local/bundle/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
     # /usr/local/bundle/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
     # /usr/local/bundle/gems/rack-2.0.6/lib/rack/null_logger.rb:9:in `call'
     # /usr/local/bundle/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
     # /usr/local/bundle/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
     # /usr/local/bundle/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:66:in `post'
     # ./spec/spec_helper.rb:30:in `api_gateway_post'
     # ./spec/server_spec.rb:36:in `block (2 levels) in <top (required)>'

Finished in 0.06118 seconds (files took 0.4499 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/server_spec.rb:22 # HelloWorld Service should POST params to API feedback endpoint with success
````

**Comment by xiangshen-dk** [comment]
Hello,

In your error message, the gems are from /usr/local/bundle/gems which seems
incorrect to me. The gems should be installed locally under a vendor
directory, which is achieved by running bundler with the '--deployment'
parameter. The odd thing is this should be taken care of automatically by
the pipeline in the build stage, if you create the pipeline using the
CloudFormation template. I just tried to reproduce the problem in a clean
account with the CloudFormation template. And it worked fine for me.

When you get a chance, can you please provide more specific steps for what
you tried?

Thanks!

**Comment by paul-e-allen** [comment]
OK, I've started everything from scratch:

1. I forked this repo into https://github.com/paul-e-allen/serverless-sinatra-sample
2. I created an GitHub personal access token
3. I created a CloudFormation stack in us-east-2 (which is a clean region for me) using https://github.com/paul-e-allen/serverless-sinatra-sample/blob/master/pipeline-cfn.yaml. That stack created successfully. Parameters:

- CodeBuildImage: aws/codebuild/ruby:2.5.1
- GitBranch: master
- GitHubToken:  ****
- GitHubUser: paul-e-allen
- GitSourceRepo: serverless-sinatra-sample

4. Upon creation of the Pipeline, a run was automatically triggered. The build stage of the pipeline failed. Here's the log:
```
[Container] 2019/04/08 11:59:40 Waiting for agent ping
[Container] 2019/04/08 11:59:42 Waiting for DOWNLOAD_SOURCE
[Container] 2019/04/08 11:59:42 Phase is DOWNLOAD_SOURCE
[Container] 2019/04/08 11:59:42 CODEBUILD_SRC_DIR=/codebuild/output/src587481721/src
[Container] 2019/04/08 11:59:42 YAML location is /codebuild/output/src587481721/src/buildspec.yml
[Container] 2019/04/08 11:59:42 Processing environment variables
[Container] 2019/04/08 11:59:42 Moving to directory /codebuild/output/src587481721/src
[Container] 2019/04/08 11:59:42 Registering with agent
[Container] 2019/04/08 11:59:42 Phases found in YAML: 2
[Container] 2019/04/08 11:59:42 INSTALL: 2 commands
[Container] 2019/04/08 11:59:42 BUILD: 2 commands
[Container] 2019/04/08 11:59:42 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
[Container] 2019/04/08 11:59:42 Phase context status code: Message:
[Container] 2019/04/08 11:59:42 Entering phase INSTALL
[Container] 2019/04/08 11:59:42 Running command pip install --upgrade awscli
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecurePlatformWarning
Collecting awscli
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecurePlatformWarning
 Downloading https://files.pythonhosted.org/packages/3d/41/f03fa1b10c7619262da75d34ce93067c9f0dc274dbd482200250319d9bef/awscli-1.16.140-py2.py3-none-any.whl (1.5MB)
Requirement already up-to-date: colorama<=0.3.9,>=0.2.5 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already up-to-date: rsa<=3.5.0,>=3.1.2 in /usr/local/lib/python2.7/dist-packages (from awscli)
Collecting botocore==1.12.130 (from awscli)
 Downloading https://files.pythonhosted.org/packages/21/80/6683916e9e1eaf867e09b81a6df6d7a2ba181e3095d2367c7a0f635ed1ed/botocore-1.12.130-py2.py3-none-any.whl (5.4MB)
Requirement already up-to-date: PyYAML<=3.13,>=3.10 in /usr/local/lib/python2.7/dist-packages (from awscli)
Requirement already up-to-date: docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from awscli)
Collecting s3transfer<0.3.0,>=0.2.0 (from awscli)
 Downloading https://files.pythonhosted.org/packages/d7/de/5737f602e22073ecbded7a0c590707085e154e32b68d86545dcc31004c02/s3transfer-0.2.0-py2.py3-none-any.whl (69kB)
Collecting pyasn1>=0.1.3 (from rsa<=3.5.0,>=3.1.2->awscli)
 Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.12.130->awscli)
 Downloading https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore==1.12.130->awscli)
 Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
Collecting urllib3<1.25,>=1.20; python_version == "2.7" (from botocore==1.12.130->awscli)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecurePlatformWarning
 Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Requirement already up-to-date: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.3.0,>=0.2.0->awscli)
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore==1.12.130->awscli)
 Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: jmespath, six, python-dateutil, urllib3, botocore, s3transfer, awscli, pyasn1
 Found existing installation: jmespath 0.9.3
 Uninstalling jmespath-0.9.3:
 Successfully uninstalled jmespath-0.9.3
 Found existing installation: six 1.11.0
 Uninstalling six-1.11.0:
 Successfully uninstalled six-1.11.0
 Found existing installation: python-dateutil 2.7.3
 Uninstalling python-dateutil-2.7.3:
 Successfully uninstalled python-dateutil-2.7.3
 Found existing installation: botocore 1.10.78
 Uninstalling botocore-1.10.78:
 Successfully uninstalled botocore-1.10.78
 Found existing installation: s3transfer 0.1.13
 Uninstalling s3transfer-0.1.13:
 Successfully uninstalled s3transfer-0.1.13
 Found existing installation: awscli 1.15.79
 Uninstalling awscli-1.15.79:
 Successfully uninstalled awscli-1.15.79
 Found existing installation: pyasn1 0.4.4
 Uninstalling pyasn1-0.4.4:
 Successfully uninstalled pyasn1-0.4.4
Successfully installed awscli-1.16.140 botocore-1.12.130 jmespath-0.9.4 pyasn1-0.4.5 python-dateutil-2.8.0 s3transfer-0.2.0 six-1.12.0 urllib3-1.24.1
/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 InsecurePlatformWarning
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 [Container] 2019/04/08 11:59:49 Running command bundle install --deployment
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from http://rubygems.org/..............
Fetching rake 12.3.1
Installing rake 12.3.1
Fetching aws-eventstream 1.0.1
Installing aws-eventstream 1.0.1
Fetching aws-partitions 1.139.0
Installing aws-partitions 1.139.0
Fetching aws-sigv4 1.0.3
Installing aws-sigv4 1.0.3
Fetching jmespath 1.4.0
Installing jmespath 1.4.0
Fetching aws-sdk-core 3.46.1
Installing aws-sdk-core 3.46.1
Fetching aws-sdk-dynamodb 1.21.0
Installing aws-sdk-dynamodb 1.21.0
Fetching aws-record 2.3.0
Installing aws-record 2.3.0
Using bundler 1.16.1
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Using json 2.1.0
Fetching mustermann 1.0.3
Installing mustermann 1.0.3
Fetching rack 2.0.6
Installing rack 2.0.6
Fetching rack-contrib 2.1.0
Installing rack-contrib 2.1.0
Fetching rack-protection 2.0.4
Installing rack-protection 2.0.4
Fetching rack-test 1.1.0
Installing rack-test 1.1.0
Fetching rspec-support 3.8.0
Installing rspec-support 3.8.0
Fetching rspec-core 3.8.0
Installing rspec-core 3.8.0
Fetching rspec-expectations 3.8.2
Installing rspec-expectations 3.8.2
Fetching rspec-mocks 3.8.0
Installing rspec-mocks 3.8.0
Fetching rspec 3.8.0
Installing rspec 3.8.0
Fetching rubysl-base64 2.0.0
Installing rubysl-base64 2.0.0
Fetching tilt 2.0.8
Installing tilt 2.0.8
Fetching sinatra 2.0.4
Installing sinatra 2.0.4
Bundle complete! 9 Gemfile dependencies, 24 gems now installed.
Bundled gems are installed into `./vendor/bundle`
 [Container] 2019/04/08 11:59:54 Phase complete: INSTALL State: SUCCEEDED
[Container] 2019/04/08 11:59:54 Phase context status code: Message:
[Container] 2019/04/08 11:59:54 Entering phase PRE_BUILD
[Container] 2019/04/08 11:59:54 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2019/04/08 11:59:54 Phase context status code: Message:
[Container] 2019/04/08 11:59:55 Entering phase BUILD
[Container] 2019/04/08 11:59:55 Running command rspec
..F.
 Failures:
 1) HelloWorld Service should POST params to API feedback endpoint with success
 Failure/Error: item.save! # raise an exception if save fails
 #<Aws::DynamoDB::Client> received :put_item with unexpected arguments
 expected: ({:condition_expression=>be a kind of String, :expression_attribute_names=>be a kind of Hash, :item=>{...g, "name"=>"Tomas", "ts"=>be within 3 of 1554724795}, :table_name=>"FeedbackServerlessSinatraTable"})
 got: ({:condition_expression=>"attribute_not_exists(#H)", :expression_attribute_names=>{"#H"=>"id"}, :item=...8400-34db-4828-b1de-fdc479f79f10", "ts"=>1554724795}, :table_name=>"FeedbackServerlessSinatraTable"})
 Diff:
 @@ -1,9 +1,5 @@
 -[{:condition_expression=>be a kind of String,
 - :expression_attribute_names=>be a kind of Hash,
 - :item=>
 - {"feedback"=>"AWS Lambda + Ruby == <3",
 - "id"=>be a kind of String,
 - "name"=>"Tomas",
 - "ts"=>be within 3 of 1554724795},
 +[{:condition_expression=>"attribute_not_exists(#H)",
 + :expression_attribute_names=>{"#H"=>"id"},
 + :item=>{"id"=>"543f8400-34db-4828-b1de-fdc479f79f10", "ts"=>1554724795},
 :table_name=>"FeedbackServerlessSinatraTable"}]
 # ./vendor/bundle/ruby/2.5.0/gems/aws-record-2.3.0/lib/aws-record/record/item_operations.rb:226:in `_perform_save'
 # ./vendor/bundle/ruby/2.5.0/gems/aws-record-2.3.0/lib/aws-record/record/item_operations.rb:80:in `save'
 # ./vendor/bundle/ruby/2.5.0/gems/aws-record-2.3.0/lib/aws-record/record/dirty_tracking.rb:275:in `save'
 # ./vendor/bundle/ruby/2.5.0/gems/aws-record-2.3.0/lib/aws-record/record/item_operations.rb:48:in `save!'
 # ./app/server.rb:64:in `block in <top (required)>'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/null_logger.rb:9:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize'
 # ./vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
 # ./vendor/bundle/ruby/2.5.0/gems/rack-test-1.1.0/lib/rack/test.rb:66:in `post'
 # ./spec/spec_helper.rb:30:in `api_gateway_post'
 # ./spec/server_spec.rb:36:in `block (2 levels) in <top (required)>'
 Finished in 0.04277 seconds (files took 0.34225 seconds to load)
4 examples, 1 failure
 Failed examples:
 rspec ./spec/server_spec.rb:22 # HelloWorld Service should POST params to API feedback endpoint with success
 [Container] 2019/04/08 11:59:55 Command did not exit successfully rspec exit status 1
[Container] 2019/04/08 11:59:55 Phase complete: BUILD State: FAILED
[Container] 2019/04/08 11:59:55 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: rspec. Reason: exit status 1
[Container] 2019/04/08 11:59:55 Entering phase POST_BUILD
[Container] 2019/04/08 11:59:55 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2019/04/08 11:59:55 Phase context status code: Message:
[Container] 2019/04/08 11:59:55 Expanding base directory path: .
[Container] 2019/04/08 11:59:55 Assembling file list
[Container] 2019/04/08 11:59:55 Expanding .
[Container] 2019/04/08 11:59:55 Expanding artifact file paths for base directory .
[Container] 2019/04/08 11:59:55 Assembling file list
[Container] 2019/04/08 11:59:55 Expanding template-export.yaml
[Container] 2019/04/08 11:59:55 Skipping invalid artifact path template-export.yaml
[Container] 2019/04/08 11:59:55 Phase complete: UPLOAD_ARTIFACTS State: FAILED
[Container] 2019/04/08 11:59:55 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found
```

**Comment by xiangshen-dk** [comment]
I found the problem and made a fix. I was testing with my other forked repo and couldn't reproduce it. Sorry, it's my bad.
When you  get a chance, please update your repo and try again. Let me know if you still have issues.
Thanks!

**Comment by paul-e-allen** [comment]
Awesome. Thank you! I can confirm that those changes fixed the problem I was having.
